### ISSUE TITLE
Missing slf4j logger binding dependency

### ISSUE THREAD

**Issue by anowak-ct** [dragon66/icafe#105]
When running a test class, I am getting the following error

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

See http://www.slf4j.org/codes.html#noProviders

**Comment by dragon66** [comment]
@anowak-ct You can add the two jar files from the Lib folder of the repository to your classpath.
