### ISSUE TITLE
Repositories are blocked on current mnv version

### ISSUE THREAD

**Issue by Exlit** [dragon66/icafe#110]
Hi! First of all thank you for such library. It was very usefull for my project. But I have an issue with building maven project now. When I am adding to pom.xml repository it says that repositories are blocked. So to make your lib work I just add the jar file to project folder but when I am building the project, I am getting: package com.icafe4j.image.meta does not exist

**Comment by dragon66** [comment]
I am not aware of the library blocked by Maven and has no idea for what reason. For temporary work, I believe you can add the Lib as a local repository and change you pom to point to it. Not portable though.

**Comment by Exlit** [comment]
Hi! Thank you for the quick response. Here is the message I am getting:
<img width="810" alt="Screenshot 2022-08-13 at 12 29 09" src="https://user-images.githubusercontent.com/41736891/184479787-872dd0f0-125b-4580-af7c-a8f9d68676f4.png">

When I am trying to install an older version of maven, I am getting: 

_Error: maven@3.5 has been disabled because it is not maintained upstream!_

It happens with all available formulas. 
So I am not sure how to solve the issue. Will thy to do the changes in pom.xml, but no luck so far.

**Comment by Exlit** [comment]
Ok. So I resolved it using this: https://stackoverflow.com/questions/4491199/build-maven-project-with-propriatery-libraries-included/4491343#4491343

Thank you again. Hope it could be useful for others.
