### ISSUE TITLE
Support javax.ImageIO JDK framework

### ISSUE THREAD

**Issue by martin1yness** [dragon66/icafe#15]
The current implementation requires that a specific API be used if this library is included. It would be ideal to become a provider of the standard API like: https://github.com/jai-imageio/jai-imageio-core

**Comment by dragon66** [comment]
Hi martin1yness, thanks for your comments.

For some historical  reason, "ICAFE" was not intended to be part of the plugin framework for Image IO API and it's structure is quite different from that of Image IO too. But yes, you've got a point here. I took a look at the linked project and it seems no longer being maintained. I forked it and will see if I can keep it going by adding more functions from "ICAFE".

Thanks

**Comment by haraldk** [comment]
Hi,

Sorry for jumping in this issue. I'm also a big fan of your work on ICafe! :-)

@martin1yness Have you considered [TwelveMonkeys ImageIO](http://haraldk.github.io/TwelveMonkeys/) (disclosure: I'm the main author)? It seems to be a good fit to the description, as it's mostly plugins for ImageIO (using the `javax.imageio` API), and adding support for many of the same formats as ICafe.


Best regards,

-- 
Harald K
