### ISSUE TITLE
Receiving the below error after downloading the jar file using mvn

### ISSUE THREAD

**Issue by kpassoubady** [dragon66/icafe#19]
Hi: The code used to work correctly, no changes made, but now I receive the below errors, can you please check:

[ERROR] [19,22] package cafe.image.gif does not exist
[ERROR] [20,17] package cafe.util does not exist
[49,32] cannot find symbol
  symbol:   variable FileUtils
  location: class com.invitae.framework.utils.CommonUtil
[ERROR] cannot find symbol
  symbol:   variable GIFTweaker
  location: class com.invitae.framework.utils.CommonUtil

**Comment by dragon66** [comment]
@kpassoubady:

Sorry to hear about that. The truth is "ICAFE" finally has a domain name to begin with and all the package names have been changed from cafe.* to com.icafe4j.* ...

**Comment by dragon66** [comment]
New Maven dependency setup:

<dependency>
  <groupId>com.github.dragon66</groupId>
  <artifactId>icafe</artifactId>
  <version>1.1-SNAPSHOT</version>
</dependency>
