### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by kpassoubady** [dragon66/icafe#23]
Hi,
  In your document, you have said, " To save memory, we can also write animated GIF frame by frame!"
  Can you provide an example? I'm getting Java Heap Space error due to all the images are written out in a single shot. 
GIFTweaker.writeAnimatedGIF(images, delays, fout);

Thanks
Kangs

**Comment by dragon66** [comment]
@kpassoubady, you can do something like this:
--java
GIFWriter animatedGIFWriter = new GIFWriter(); 
53 		animatedGIFWriter.setImageParam(builder.applyDither(true).build()); 
54 		// Set logical screen width and height to zero to use first frame width and height  
55 		GIFTweaker.prepareForWrite(animatedGIFWriter, fout, 0, 0); 
56 		for(int i = 0; i < images.length; i++) 
57 			GIFTweaker.writeFrame(animatedGIFWriter, fout, images[i]); 
58 		// wrap it up 
59 		GIFTweaker.finishWrite(fout); 
---

**Comment by kpassoubady** [comment]
Thank You so much. Your input helped a lot.


Thanks
Kangs

Kangeyan Passoubady
