### ISSUE TITLE
compile Java 1.6 support

### ISSUE THREAD

**Issue by jhidalgo93** [dragon66/icafe#28]
This library can compile the java 1.6?

I have a problem using classes as my contender this in java 1.6

**Comment by dragon66** [comment]
Hi @jhidalgo93,

The source code of this library is Java 1.5 compliant. I compiled it using Java 1.7 without explicit setting code compliance. So if you use the compiled code with Java 1.6, it won't work. You can either compile the source code using version 1.6 or grab a new build soon.

**Comment by jhidalgo93** [comment]
You could release a version compiled in Java 1.6 because in my work environment can not use maven to do it myself ?

**Comment by dragon66** [comment]
New build version with 1.5 compliant is done it should work with higher version of Java like 1.6

**Comment by jhidalgo93** [comment]
In the repository is also the upgrade ?

https://oss.sonatype.org/content/repositories/snapshots

**Comment by dragon66** [comment]
Yes, it is icafe-1.1-20160420.232009-61.jar

**Comment by jhidalgo93** [comment]
You 're the best friend .

Tomorrow when I get to the office I 'll try thanks

**Comment by jhidalgo93** [comment]
i have error 

java.lang.UnsupportedClassVersionError: com/icafe4j/image/options/ImageOptions : Unsupported major.minor version 51.0 with new version library

**Comment by jhidalgo93** [comment]
I run the class verifier and the output is the following

class file version is 51.0
You need to use JDK 7 or above

Please help me friend

**Comment by dragon66** [comment]
I know why it failed. I still need a compiler lower or equal 1.6 to make it works for you case. I don't have one installed on my machine. That's why I didn't compile it using a 1.6 compiler. I will compile it again later with a 1.5 compiler

**Comment by jhidalgo93** [comment]
I thank him immensely friend

**Comment by dragon66** [comment]
See the new build which is supposed to be 1.5 binary compatible.

**Comment by jhidalgo93** [comment]
thanks friend

**Comment by Lodurnorbel** [comment]
Hi, I downloaded your last version and can't compile it in Java 1.6.
I can't upgrade the version of my compiler so, could you help me with this issue?
Thank you very much.

**Comment by dragon66** [comment]
@Lodurnorbel what is the error message did you get? I only used Java 1.5 compatible features for ICAFE so there should be no issue to compile it using Java 1.6.

**Comment by jhidalgo1** [comment]
i have a stable version , you can write me apoloeam@gmail.com

**Comment by Lodurnorbel** [comment]
Hi @dragon66, thanks for your early response
If I use the last version and I set up my project on Java 1.6 I get the following message: 
`major version 51 is newer than 50, the highest major version supported by this compiler.`

And then, if I zip the folder in "build" folder with all the classes, I get this error:
`error: error reading ..\icafe-master\icafe-master\build\classes\icafe.jar; error in opening zip file
1 error
..\nbproject\build-impl.xml:957: The following error occurred while executing this line:
..\nbproject\build-impl.xml:292: Compile failed; see the compiler error output for details.`

I don´t know if I did it in a bad way the second time, and I would like to know how to do it well.
Thank you very much.

**Comment by dragon66** [comment]
@Lodurnorbel looks like something is wrong with the settings when generating the build. I remember set it to Java 1.5 compliant. If you download the source without using the pre-compiled library, you should be able to compile it using Java 1.6.
