### ISSUE TITLE
How do you change the dpi of tif-file  ?

### ISSUE THREAD

**Issue by cod91** [dragon66/icafe#30]
How do you change the dpi of tif-file?

**Comment by dragon66** [comment]
@cod91 That's one the thing I left out when I wrote the TIFF writer and related stuff. I thought about put that into the code before but never really did it. I believe it could be done this way: add a new parameter to GIFOptions for DPI and add a check to TIFFWriter for the DPI and add a new TIFF field to the output image.

I will take a look at it when I have time later

**Comment by dragon66** [comment]
Added new parameters to TIFFOptions to set X resolution, Y resolution, as well as resolution unit.
```
TIFFOptions tiffOptions = new TIFFOptions();
		  		 tiffOptions.setXResolution(96);
		  		 tiffOptions.setYResolution(96);
                                 tiffOptions.setResolutionUnit(ResolutionUnit.RESUNIT_INCH);
```

**Comment by cod91** [comment]
Thank you for helping us take time
