### ISSUE TITLE
Add extra info to closed issue #29

### ISSUE THREAD

**Issue by huffstler** [dragon66/icafe#32]
This isn't about iCafe per se. 

I would like to add some extra information to the bottom of issue #29 (which is closed) to help others who come across it, like I did.

If you can add this (or open it for a short amount of time, so I can include one more comment) I'll add the following at the very bottom:

`I would like to leave a comment for anyone else who might find this while searching for a fix to their problems (like I did). The built in concurrency mechanism that dragon66 is talking about is the synchronize() block. Info about it can be found [here](https://docs.oracle.com/javase/tutorial/essential/concurrency/locksync.html).`

**Comment by dragon66** [comment]
@huffstler I reopened the issue so that you can add your comments. Thanks for your consideration!

**Comment by huffstler** [comment]
Thank you very much! Everything is added.
