### ISSUE TITLE
Any example of how to write info into XMP ?

### ISSUE THREAD

**Issue by ivanooi** [dragon66/icafe#34]
Hi,

Any example of how to write info into XMP ?

Found this but going no where...
JpegXMP

Thanks

**Comment by dragon66** [comment]
Up to now, icafe doesn't contain any API to create XMP itself. I once opened an enhancement issue for this but didn't carry it out. If you want to create XMP document itself, try Adobe [Java XMP API](http://www.adobe.com/devnet/xmp/library/eula-xmp-library-java.html)

**Comment by dragon66** [comment]
I have reopened the following [issue](https://github.com/dragon66/icafe/issues/8)  in the hope that I will give it another try some day.

**Comment by ivanooi** [comment]
I see.... but Adobe XMP is a read only API. No write API. and I found out Apache Imaging failed to handle array elements which used by MS. as you pointed out in previous message. 

great! Thanks!

**Comment by dragon66** [comment]
@ivanooi This blog talks about CC License Tagging which uses Adobe API and ICAFE to create and insert XMP to image for Creative Commons. You may find it useful too.
