### ISSUE TITLE
How to covert tif to jpeg use icafe? Thanks..

### ISSUE THREAD

**Issue by ilvZuo** [dragon66/icafe#35]
How to covert tif to jpeg use icafe? Thanks..

**Comment by dragon66** [comment]
@ilvZuo To convert TIFF to JPEG, you need first read it into a BufferedImage and write it in JPEG format. ICAFE currently partially support reading TIFF and if you find it couldn't read your TIFF, use the included jai-imageio library to read it and use icafe to save as JPEG.
