### ISSUE TITLE
Does com.icafe4j.image.ImageIO write interlaced images?

### ISSUE THREAD

**Issue by magiclen** [dragon66/icafe#37]
Your project is very perfect. But it seems that it does not support the export of interlaced GIF, PNG and JPG images. Or maybe I didn't find it.

**Comment by dragon66** [comment]
@magiclen no, it doesn't. First of all, personally I don't see a lot of practical usage for it nowadays given the improvement of hardware. Second, it is harder and inefficient to write interlaced images.

**Comment by magiclen** [comment]
I see, you have done well!

I prefer interlaced images, so I will use my way to convert them(ImageMagick is a great tool to do that).

Thanks for your prompt reply!
