### ISSUE TITLE
Can't delete anything from IPTC metadata and preserve Clipping Path.

### ISSUE THREAD

**Issue by sinedsem** [dragon66/icafe#40]
Some people insert outlines in their JPEG images, which are named "Clipping path". There are a few articles about this, e. g. http://designus.sk/the-secret-path-of-jpg-images/

Here I have an example of image with clipping path: https://github.com/sinedsem/test/blob/master/clipping_path.jpg

In addition to clipping path, this image has one IPTC Keywords tag - keyword.
Let's say I want to remove this tag from image, but save clipping path info. Unfortunately, I can't do this.

When I call insertIPTC with update = true, clipping path is saved, but I can't delete tags, only add.
When I call with update = false, I see no way to preverve clipping path.

That's how I use it:

```
File source = new File("clipping_path.jpg");
File destination = new File("result.jpg");
FileInputStream is = new FileInputStream(source);

Map<MetadataType, Metadata> metadataMap = Metadata.readMetadata(is);

ArrayList<IPTCDataSet> iptcDataSets = new ArrayList<>();

// the following loop is needed to preserve all metadata but Keywords. Unfortunately, I can't retrieve clipping path from here.
if (metadataMap != null && metadataMap.get(MetadataType.IPTC) != null) {
    IPTC iptc = (IPTC) metadataMap.get(MetadataType.IPTC);
    for (Map.Entry<String, List<IPTCDataSet>> entry : iptc.getDataSets().entrySet()) {
        if (!entry.getKey().equals(IPTCApplicationTag.KEY_WORDS.getName())) {
            System.out.println(entry.getKey());
            iptcDataSets.addAll(entry.getValue());
        }
    }
}

is = new FileInputStream(source);
FileOutputStream os = new FileOutputStream(destination);

Metadata.insertIPTC(is, os, iptcDataSets, true); // this can be true or false

is.close();
os.close();
```

**Comment by sinedsem** [comment]
As I see from text editor, a significant part of metadata is being cut off when calling `insertIPTC(.., .., .., false)`, which is defenitely not an IPTC

>         x8BIM        8BIMу     	         8BIM
>        8BIM'     
>         8BIMх     H /ff  lff       /ff  Ў™љ       2    Z         5    -        8BIMш     p  яяяяяяяяяяяяяяяяяяяяяяи    яяяяяяяяяяяяяяяяяяяяяяи    яяяяяяяяяяяяяяяяяяяяяяи    яяяяяяяяяяяяяяяяяяяяяяи  8BIM          @  @    8BIM         8BIM    I             ђ  ђ   
>  U n t i t l e d - 1                                ђ  ђ                                            null      boundsObjc         Rct1       Top long        Leftlong        Btomlong  ђ    Rghtlong  ђ   slicesVlLs   Objc        slice      sliceIDlong       groupIDlong       originenum   ESliceOrigin   
> autoGenerated    Typeenum   
> ESliceType    Img    boundsObjc         Rct1       Top long        Leftlong        Btomlong  ђ    Rghtlong  ђ   urlTEXT         nullTEXT         MsgeTEXT        altTagTEXT        cellTextIsHTMLbool   cellTextTEXT        	horzAlignenum   ESliceHorzAlign   default   	vertAlignenum   ESliceVertAlign   default   bgColorTypeenum   ESliceBGColorType    None   	topOutsetlong       
> leftOutsetlong       bottomOutsetlong       rightOutsetlong     8BIM(        ?р      8BIM        8BIM    Ђ             а ,   d  яШяа JFIF   H H  ян Adobe_CM яо Adobe dЂ   яЫ „ 			
> 
> 
> 
> яА     " яЭ  
> яД?          	
>          	
>  3 !1AQa"qЃ2‘Ў±B#$RБb34r‚СC%’Sрбсcs5ўІѓ&D“TdEВЈt6ТUвeті„ГУuгуF'”¤…ґ•ДФдфҐµЕХехVfv†–¦¶ЖЦжц7GWgw‡—§·ЗЧзч 5 !1AQaq"2Ѓ‘Ў±B#БRСр3$bбr‚’CScs4с%ўІѓ&5ВТD“TЈdEU6teвті„ГУuгуF”¤…ґ•ДФдфҐµЕХехVfv†–¦¶ЖЦжц'7GWgw‡—§·ЗяЪ   ? хT’I%)$’IJI%Зэgя ЯWєџЏKїig°ђh ЌЌp0[~O№•я RїZЦ„­%=‚ЈФzЯGйcьЈ›F!#s[uЌc€ёЗпюВро№ю3ѕ¶urж7'ц~9:S‰5ќ'йdOЪ]ьїТъ_рK•sњч8—9Ж\г©$ч))чЊїсіх+MyVe8~m4ѕОИmя ¦іПшлъ­Ы?юЫ§я z—‹$’џjгЇк±з<Цйя Ю•Ґ‡ю5>Ґd†‡f»о0uVуџ[-Ґїцвр4’SфюUйќI…э?.њ¶·й,m‘?їй№ЫUµтЅW[EЌє—є«Xe–0–ё№ѕж®Г я Ќo­)МЇ.СХ1D^Oу‘2н™mэ.ч~цGЪЁ’џxIsV?ЖХп¬{(ЄЯІg»юСЯ
> q0'РіщјЏмю›ю‹§IJI$’R’I$”я яРхT’I%)VкC¦aЫќџsqсhnл- yG№пwС®¶~’Зы+KЁх>™ѓv~uўЊ\vпІЗv ?yпwІ¶„±xЧO®№я Zs·8єћќKЏЩq'AЫЦє>ќоoэ·ьЭi)Цъзю4z—\/ВйEш0‚ЧA‹®џYмюj­їа*я ЇYjб’I%)$’IJI$’R’I$”¤’I%)z/Фїс±™Ђкр>±=щxeА74Л®Ё?KщЩT·йЬџшя СТјй$”эMЏ‘FUИЖ±·QkC«µ„9®iбНs}®D^хлоWХњ¦гd№Чt‹ќъjy5“я j1я фeбгјcдQ•Ey8пУsCк±¦Zжёnkљ”Ф”‘$’IOяСхT’\?шЧъРоЌРїgвїnoTЭX"%”й/бЯОnфя e•я 2’ћьf}t?XzџШ0џюJАyђe·Z%ЏКцыvѓЖя ѓэ/шMqi$’”’I$Ґ$’I)I$’JRI$’”’I$Ґ$’I)KСЕ?ЧG`f3ко}Ћ8yoЊ'"«њ™ЧиУ”пЭя µ?™ъ{¬^t’J~ЄIsвул?ьгъЅU·їv~'и3’\Съ<Ќія j+чnя Oля Ј]:JяТхUу·ЧЮЅыwлFf[ї—}џѓ#ТЁ–‡°Ац]g©‘я ^^бхГЄ»ЈэXк]AЋ,ІЄKi{ym¶F=юЕЦЦѕnIJI$’R’I$”¤’I%)$’IJI$’R’I$”¤’I%)$’IOeю*zуєWЦЉ±,|bхAцk&=OҐ€эЈй?Хэ]їшeлЮКфЫmІк\YmN­гBУ№®oх\ѕќйYмк]3Ё0mn]5ЮМzЌm›?і№%?яУЧя щn§кЅмt¬¶5нсcm§я m+ДЧ«я Џ;+иХюkЋK€уhЖю­yBJRI$’”’I$Ґ$’I)I$’JRI$’”’I$Ґ$’I)I$’JRчПсW2~Ґa4ё№шО¶—“еcмcіMµЇ^Хю%э‹eы?уО*JяФсжТ[С_Ш O™ы/юEyJцЏсХ‹к}[ЕЙ
> %Шщmш2ЖZя ‚2Ґвй)I$’JRI$’”’I$Ґ$’I)I$’JRI$’”’I$Ґ$’I)KЪД я ±lія wмя П8«Е—јя ЉlAЏх+БЈІ¬єз=оЗoэ
> ’џяХо>јфЗuOЄ]OЂ›=maўI}$d±Ќя Њu>љщЙ}TѕpъзРЏAъЙ›УГvРкbу›?INТп§йO чҐ©й)ДI$’R’I$”¤’I%)$’IJI$’R’I$”¤’I%)$’IKµ®{ѓZњг
> hФ’{фЯDйГҐф|.ќ њJ+ҐОnЂ№Ќ
> {я ¶я zрпсcРПWъЩЊзґњ~џъЭЗЌk#мнгуІ}/gъ/U{ъJяЦхUзїг{к№к=)ќo›Ієh"р®Ж>зџk\з}•я ҐэЖRь«Ў(ЅЊ{Зґ9Ћ9¤H тЧ”ь®’кЖФл>¬хrhoщ+,—бѕK¶юю-…Юнфюfпзiья SХЩЛ$Ґ$’I)I$’JRI$’”’I$Ґ$’I)I$’JRI.зьWэL=s©«љАzfБШб"л‡Ѕ”ЗСфЄцЫэnџрѕД§РЕЏХ‡t«Н»%…™эF/ИжІ?VЎАя ЈcЅGюе·YZмI%?яЧхT’I%9эwЎфоЅУmйЅFЅф[Ёst{>…Фї]–Чя ЁмЯVъЧПЯZѕЄх/«Hбж
> фѕ]‹”Сµѓу›ОЛY?¦§ьь_ҐmџH¬ю№Рєo^йЦtоҐW«CэН#G±ги]Kя БЪЙя Сv~‰ц1%?2¤єџ®?вы«эY±ЧЂrъYЌ™ЊFNС^S?Аїwзя 3gьgи™Л$Ґ$’I)I$’JRI$’”’I$Ґ$’н>Ґя ‹>§х„і7?~J0E„E·оэUЏьНїц¦ПСя ўхя H’њп©_Rуѕґз†·u=:—µеGџF™цєчя аОXЅы§фь>™…N
> MЈ»*­јПцћч{м±Юы,э#ТйЭ;¦aХѓЃKqсik­њ2O№пwзШя ТX¬¤Ґ$’I)яРхT’I%)$’IL^Ж=ЋcЪЗТ$yk‚а>ґЉ•ФKтє#ЗMКt“AЊго:1ѕь]О?а·ТЖ}eи)$§з»х3л'A.=C	в†я ЪЄя IIґ;Ц®}=я №wҐoт"ъ©au?ЁЯTє«‹у:e>Ў$›*—’9пЖ5:ПъвJ~rI{FWш•ъ·fгЌ•—ЋвtМ±ѓы&¦Yя ‚¬Ч€Ж“млDАвЙя Ы¦¤§КR^Ї_шЊ¬;фќd№ЅГqѓOЮr^µq?ДЗХz\Чд_—”GТcћЖ0ьЄ©¶я аЙ)с5РфЁ?Z:оЗвaєњgБYUPx{‡©s?рЅw/pй_Sю¬tw5э?¦УUЊ;™s‡©cOт/И6ЬЯуЦКJxЄя вЈЎtg3+ЁЪ™­Ф0я #Эк}/§©ю’єй]ВI$Ґ$’I)I$’JяЩ8BIM!     U       A d o b e   P h o t o s h o p    A d o b e   P h o t o s h o p   C S 3    8BIM    Ф                                                     
>                        	> hъ ® vff ѓІ ѓIЁ  ъш Џз* 
> ЭY ›ЮT sV Єѕћ  Gд ёќК Ђд ДВ: -я Э  Gv¬ оћ d0щ хђа {@ ы‡  ”ц ъ—ы Ї\( п\( ОЅї в•  дЙХ М
> Ц рС «ё фё‰ Ў:V  ццe •qd шлл €Еµ ы€” wб  цЩ‡ g„Х тьЂ Xд р L`  и~* ?ві Я¤І 4Аё Ф—• &Щ¬  Ж±п ЌЬ ґ+" @‡ ©4> 
> V·  њме 	1K ђHЁ tc |5 ±У  g7E щХ Uё z 4щщ Ік  фЎ 3­* \( SЧ
>  F" ^F                        ќюO°”і ќюO°”і ќюO°”і8BIM          явXICC_PROFILE   HLino  mntrRGB XYZ О  	  1  acspMSFT    IEC sRGB             цЦ     У-HP                                                 cprt  P   3desc  „   lwtpt  р   bkpt     rXYZ     gXYZ  ,   bXYZ  @   dmnd  T   pdmdd  Д   €vued  L   †view  Ф   $lumi  ш   meas     $tech  0   rTRC  <  gTRC  <  bTRC  <  text    Copyright (c) 1998 Hewlett-Packard Company  desc       sRGB IEC61966-2.1           sRGB IEC61966-2.1                                                  XYZ       уQ    МXYZ                 XYZ       oў  8х  ђXYZ       b™  ·…  ЪXYZ       $   „  ¶Пdesc       IEC http://www.iec.ch           IEC http://www.iec.ch                                              desc       .IEC 61966-2.1 Default RGB colour space - sRGB           .IEC 61966-2.1 Default RGB colour space - sRGB                      desc       ,Reference Viewing Condition in IEC61966-2.1           ,Reference Viewing Condition in IEC61966-2.1                          view     ¤ю _. П нМ  \ћ   XYZ      L	V P   Wзmeas                         Џ   sig     CRT curv          

**Comment by sinedsem** [comment]
Very similar issue on SO for Objective-C, with no provided solution =(
http://stackoverflow.com/questions/32160528/read-non-standard-properties-from-an-image-in-objective-c

**Comment by sinedsem** [comment]
This article https://www.graphicsmill.com/docs/gm/clipping-path.htm says that 

> Clipping paths are stored in Adobe image resource blocks in TIFF, JPEG, and PSD image formats.

so I don't think that `insertIPTC` should remove them.

**Comment by sinedsem** [comment]
I tried going a little more deeper, and that's what I've found:

```
File source = new File("clipping_path.jpg");
File destination = new File("result.jpg");
FileInputStream is = new FileInputStream(source);

Map<MetadataType, Metadata> metadataMap = Metadata.readMetadata(is);
System.out.println(metadataMap.get(MetadataType.PHOTOSHOP_IRB)); // here we have PHOTOSHOP_IRB, where, as I hope, clipping path is stored.

ArrayList<IPTCDataSet> iptcDataSets = new ArrayList<>();
// no more loop here

is = new FileInputStream(source);
FileOutputStream os = new FileOutputStream(destination);

Metadata.insertIPTC(is, os, iptcDataSets, false); // false, just insert empty IPTC

is.close();
os.close();

metadataMap = Metadata.readMetadata(destination); // IllegalArgumentException !!!
System.out.println(metadataMap.get(MetadataType.PHOTOSHOP_IRB));
```

Stack Trace:

    java.lang.IllegalArgumentException: Copy range out of array bounds
	at com.icafe4j.util.ArrayUtils.subArray(Unknown Source)
	at com.icafe4j.image.meta.adobe.IRB.read(Unknown Source)
	at com.icafe4j.image.meta.Metadata.ensureDataRead(Unknown Source)
	at com.icafe4j.image.meta.adobe.IRB.get8BIM(Unknown Source)
	at com.icafe4j.image.jpeg.JPEGTweaker.readMetadata(Unknown Source)
	at com.icafe4j.image.meta.Metadata.readMetadata(Unknown Source)
	at com.icafe4j.image.meta.Metadata.readMetadata(Unknown Source)

**Comment by dragon66** [comment]
@sinedsem When you call insertIPTC with update = true, it basically says keep all the other stuff from Photoshop IRB and insert IPTC. Otherwise it will replace the whole IRB with only the IPTC inserted. That is what you have seen with your test and that is exactly what icafe is supposed to do. 

I am not sure what do you mean by saying "I can't delete tags, only add." What tags are you trying to delete? You want to delete tags for IPTC and failed?

Also if you want to remove IPTC, you can call 

> Metadata.removeMetadata(fin, fout, MetadataType.IPTC)

 which takes variable number of arguments. I used this call to remove the IPTC in the original image and it works fine.

**Comment by sinedsem** [comment]
@dragon66 Yes! Thank you very much for the answer!

What I am trying to do is to delete all `IPTCApplicationTag.KEY_WORDS` entries from my image and then insert another `IPTCApplicationTag.KEY_WORDS` entries, but preserve **all** other information that was in image.

The way you've described works perfectly: firstly call `removeMetadata(.., .., MetadataType.IPTC)` to get rid of all previous IPTC, then `Metadata.insertIPTC(.., .., .., true)` to insert new IPTC.

But still, there are a few unclear points for me. Did I get it right from your words that IPTC is a **part of** IRB? This would explain your first sentence. And this also would explain, why I can't delete `IPTCApplicationTag.KEY_WORDS` that are already in image just by calling `Metadata.insertIPTC(.., .., Collections.emptyList(), true)` without previuosly calling `removeMetadata(.., .., MetadataType.IPTC)`

I have another question for you. My application allows to edit IPTC and XMP metadata. Is there a way to achieve this without copying the whole image 3 times in a row? I mean, now I need to:

```
File stepOneTempFile = File.createTempFile(TEMP_FILE_PREFIX, ".jpg");
File stepTwoTempFile = File.createTempFile(TEMP_FILE_PREFIX, ".jpg");
File stepThreeTempFile = File.createTempFile(TEMP_FILE_PREFIX, ".jpg");

FileInputStream is = new FileInputStream(sourceFile);
FileOutputStream os = new FileOutputStream(stepOneTempFile);
Metadata.removeMetadata(is, os, MetadataType.IPTC);
is.close();
os.close();

// creating iptcDataSets
is = new FileInputStream(stepOneTempFile);
os = new FileOutputStream(stepTwoTempFile);
Metadata.insertIPTC(is, os, iptcDataSets, true);
is.close();
os.close();

// creating xmp
is = new FileInputStream(stepTwoTempFile);
os = new FileOutputStream(stepThreeTempFile);
Metadata.insertXMP(is, os, xmp);
is.close();
os.close();

FileUtils.copyFile(stepThreeTempFile, sourceFile);

stepOneTempFile.deleteOnExit();
stepTwoTempFile.deleteOnExit();
stepThreeTempFile.deleteOnExit();

```

**Comment by dragon66** [comment]
@sinedsem To answer your question:
1. Yes, IPTC is one of the 8BIM block. All the 8BIM blocks together become Photoshop IRB (Image Resource Block) metadata. It is actually called IPTC_NAA ( You can find an entry from ImageResourceID.java for it called IPTC_NAA("IPTC-NAA record.", (short)0x0404)). In the testing image you provided, the Working Path 8BIM block is right before the IPTC_NAA 8BIM block.

2. The reason why you can't delete that keyword by inserting a new IPTC keyword is actually due to the fact that IPTC allows multiple keywords to be inserted. Because of that, in my implementation, icafe will not override the keyword tag value instead it would create a list for all the keyword values including the old one. In IPTCApplicationTag.java enum, you will be able to find a method called allowMultiple() which controls whether or not the corresponding tag allows multiple.

3. This is a bit complicated. Manipulating metadata is not as easy as removing metadata which can be done in a single swoop without messing up the whole structure. Not that it is not doable but that it would be memory consuming as we have to put the whole image structure tree into the memory. Another challenge is we have to maintain certain sequence for different metadata types along with the other parts of the image.

Given the above reason, currently, there is no easy way for icafe to manipulate more than one metadata type at a time. This may be changed at a later time.

**Comment by sinedsem** [comment]
Thanks, I am completely fine with your answers.

**Comment by dragon66** [comment]
@sinedsem By the way, thanks for offering a beer! That's exactly what I need sometimes to keep icafe rolling given the workload I have day to day.

**Comment by sinedsem** [comment]
@dragon66 I insist you answer my email sent today..

**Comment by dragon66** [comment]
@sinedsem I actually found that you can use two steps instead of three steps to add both IPTC and XMP. Using the following step to replace removing and inserting IPTC:
```
Metadata.insertIRB(fin, fout, createPhotoshopIPTC(), true);
```
Here is the createPhotoshopIPTC():
```
private static List<_8BIM> createPhotoshopIPTC() {
		IPTC_NAA iptc = new IPTC_NAA();
		iptc.addDataSet(new IPTCDataSet(IPTCApplicationTag.COPYRIGHT_NOTICE, "Copyright 2014-2016, yuwen_66@yahoo.com"));
		iptc.addDataSet(new IPTCDataSet(IPTCApplicationTag.KEY_WORDS, "Welcome 'icafe' user!"));
		iptc.addDataSet(new IPTCDataSet(IPTCApplicationTag.CATEGORY, "ICAFE"));

		return new ArrayList<_8BIM>(Arrays.asList(iptc));
	}
```

**Comment by dragon66** [comment]
@sinedsem, on second thought, I believe this one has something related to the issue #41. After my fix for that one, I believe you can actually user insertIPTC with update = false to remove all the original IPTC and insert new IPTC at the same time. So only two steps are needed if you want to insert both IPTC and XMP.

**Comment by sinedsem** [comment]
@dragon66 thanks a lot, I did as you suggested. In addition, I don't save to file between two steps (iptc and xmp), I save to byte array (using ByteArrayInputStream and ByteArrayOutputStream), this makes all even faster!

**Comment by dragon66** [comment]
@sinedsem I added support to insert metadata to JPEG image in one step. You can check the TestMetadata.java for more details.

**Comment by ibrahimrajabli** [comment]
hi dragon66. i need help. where i can write question? here? i ask here yet. 
 first my exception and after code
```

Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at com.icafe4j.image.meta.Metadata.<clinit>(Unknown Source)
	at vectorcleaner.Metadata1.populateExif(Metadata1.java:41)
	at vectorcleaner.Metadata1.main(Metadata1.java:127)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more
C:\Users\rajab\AppData\Local\NetBeans\Cache\8.2\executor-snippets\run.xml:53: Java returned: 1
```
`BUILD FAILED (total time: 0 seconds)`




```
  
  private static List<IPTCDataSet> createIPTCDataSet() {
  	List<IPTCDataSet> iptcs = new ArrayList<IPTCDataSet>();
  	iptcs.add(new IPTCDataSet(IPTCApplicationTag.COPYRIGHT_NOTICE, "Copyright 2014-2016, yuwen_66@yahoo.com"));
  	iptcs.add(new IPTCDataSet(IPTCApplicationTag.CATEGORY, "ICAFE"));
  	iptcs.add(new IPTCDataSet(IPTCApplicationTag.KEY_WORDS, "Welcome 'icafe' user!"));
  	
  	return iptcs;
  }

  private static IPTC createIPTC() {
  	IPTC iptc = new IPTC();
  	iptc.addDataSets(createIPTCDataSet());
  	return iptc;
  }

public static void main(String[] args) throws  IOException {
  FileInputStream fin = new FileInputStream("C:/Users/rajab/Desktop/test/ibo.jpeg");
  FileOutputStream fout = new FileOutputStream("C:/Users/rajab/Desktop/test/ibo/ibo.jpeg");

  List<Metadata> metaList = new ArrayList<Metadata>();
  metaList.add(populateExif(TiffExif.class));
  metaList.add(createIPTC());
  metaList.add(new Comments(Arrays.asList("Comment1", "Comment2")));
  
  Metadata.insertMetadata(metaList, fin, fout);
}
}
```

**Comment by dragon66** [comment]
@ibrahimrajabl when you do the build please include the jars in the lib folder. This will fix the issue.

By the way, you should open a new issue instead.

Wen
