### ISSUE TITLE
Support for writing 48bpp pngs? [question]

### ISSUE THREAD

**Issue by wkaczurba** [dragon66/icafe#46]
I spent a bit of time playing with demos but I have failed to produce 48bpp png.
Does icafe support it? Is there a plan to support writing deep color pngs?

Thanks.

**Comment by dragon66** [comment]
@wkaczurba icafe doesn't support writing PNG with bits per color more than 8. By 48bpp PNG I assume you mean 16 bits per color totaling 48bpp without taking care of the alpha channel. I have no plan to add this function in the near future as I already has a few high priority items to work on.
