### ISSUE TITLE
No instructions on what jar(s) to use...

### ISSUE THREAD

**Issue by adanecito** [dragon66/icafe#48]
Hi,
I want to read a jpeg from a servlet and can not find instructions on what jars to use. You have two main jars one 980kb and the other 2Mb so not sure why two and which to use and if there are more needed for compile and deploy.

**Comment by dragon66** [comment]
@adanecito All you need are the jars inside the lib folder. In there, you can choose the ***snapshot** which does not include the documents. This makes it smaller size. So the jars are
