### ISSUE TITLE
can have any idea on android?

### ISSUE THREAD

**Issue by bigsquirrel** [dragon66/icafe#5]
most open source lib support is not good.

**Comment by dragon66** [comment]
There are more some requirements from users to be able to use the metadata management functionality in Androit. Thinking about creating a new repository for metadata related code which will be standalone without dependency on java.awt.* package.

**Comment by dragon66** [comment]
Ported to Android and created new pixymeta-android repository. Not yet tested on Andorid device. Need help to do it.

**Comment by dragon66** [comment]
Tested pixymeta-android with Nexus4 virtual device. Close this issue here, any further issues to pixymeta-android repository.

**Comment by ivanooi** [comment]
Hi, does pixymeta-android features same as current？ 

Thanks

**Comment by dragon66** [comment]
It's kind of old. I haven't work on this for quite a while.

**Comment by ivanooi** [comment]
Is there anyway that I can use the lastest icafe and mix with pixymeta-android? I love the current icafe features. especially the way it handle EXIFT and XMP

**Comment by dragon66** [comment]
@ivanooi you can't mix them together. I will try to update them hopefully soon.

**Comment by ivanooi** [comment]
thanks :-D  Especially EXIF and XMP

**Comment by dragon66** [comment]
@ivanooi I did some change to the pixymeta-android according to your request. Can't guarantee I have caught all the changes made in ICAFE. If you found anything inconsistent, just let me know.

**Comment by ivanooi** [comment]
wow! Thanks!!
