### ISSUE TITLE
icafe jar is incompatible with jre1.5

### ISSUE THREAD

**Issue by rav17** [dragon66/icafe#50]
Hi,

i am unable to use icafe in my project because it runs on java 1.5 version and icafe jar file is compiled with version 1.7.

can i get icafe jar file compile in 1.5.

**Comment by allhands8** [comment]
I also can not use on java1.5. 
but developer dragon66 said it can works on java 1.5
Is there anyone who know about it???

**Comment by sinedsem** [comment]
OMG @allhands8 why do you need java 1.5 in 2017? 
If you really need java 1.5 you can compile icafe yourselves. But I personally with icafe to migrate to java 8

**Comment by dragon66** [comment]
As a result of not being able to access a personal computer, I haven't been able to do any new Maven publish for quite a long time. I can't provide help regarding this for the time being.

**Comment by dragon66** [comment]
The current code is compiled using Java 8. The source code it self is 1.5 compliant.
