### ISSUE TITLE
A few questions about icafe

### ISSUE THREAD

**Issue by sinedsem** [dragon66/icafe#53]
Hello @dragon66!

It's me again. I would like to thank you again for your library. I respect that you support it and keep it free and open source.

However, I can see that you are not so passionate about icafe. I don't see new features are being implemented or enhancement issues are being closed. As a developer I can fully understand you.

But I don't want this project to die, so I think I will fork it and will try to implement some features that I need and possibly add some improvements. And here I need your help:

1. I can't debug icafe. Breakpoints in IDEA are missed and debugger walks between methods. Do you use any plugins like lombok which may affect debugging?
2. How did you implemented all this stuff? Did you follow any documentation, standards? Can you please share the docs/articles?

Please say if you find this appropriate.
Thanks,
Denis,
StockHelper developer.

P. S. You icafe certainly deserve to be built with Maven. This will be the first improvement I am going to add.

**Comment by dragon66** [comment]
@sinedsem There have been quite a few things recently which have prevented me from adding new features and fixing some of the issues but ICAFE will not die for sure. 

You are always welcome to fork and improve icafe.  
As for the questions you asked:
1. I use Eclipse and there is no issue in debugging icafe.
2. Most of the ICAFE features were implemented during year 2013-2014 but the codecs of a few image types were done over 15 years ago. In the process of development, I consulted specs I could find, third party documents, sometimes psedo code, other's work, and even research articles. I do have some documents for different features but they all sit on my home computer which is broken by my son and that's is one of the reason ICAFE development is at a stand-still. I will share them later when I can.

I remember ICAFE contains a Maven build file itself, right?

By the way, I believe you can also contribute directly to ICAFE as a contributor without fork it if you want.

Wen

**Comment by sinedsem** [comment]
Ok, thanks for the reply. I will investigate your code and return with questions. I think I will use this thread to communicate

**Comment by dragon66** [comment]
@sinedsem I can point you to some documents related to tiff. If you want, let me know.

For now, I am going to close this question.
