### ISSUE TITLE
JPEGTweaker.insertMetadata throws NullPointerException

### ISSUE THREAD

**Issue by StefanGohlke** [dragon66/icafe#60]
Hello,

in icafe-1.1-SNAPSHOT in class JPEGTweaker a NullPointerException may occur in function insertMetadata( starting at line 1063).

`if(eightBIMStream != null) {
					...				
				  	}
					eightBIMStream.reset();`

Calling  eightBIMStream.reset() outside the null check resulted in a NullPointerException. It would be wise to add an else condition to create a new ByteArrayOutputStream to ensure  eightBIMStream is not null if we want to work with it in the following lines.

Sincerely yours,
Stefan

**Comment by dragon66** [comment]
@StefanGohlke Thanks for pointing this out. I have changed the code and checked in. I have some issue publish on Maven though.
