### ISSUE TITLE
Help resizing animated gif

### ISSUE THREAD

**Issue by kfredy** [dragon66/icafe#61]
Hi,
I'm trying to resize a big 4M animated gif (I'm using GifDecoder but i'm getting out of Memory Exception so trying iCafe :-)). Note that i do not have access to disk so i need to resize frame by frame. (You have a note on that on the wiki but i could not figure out the process...)
i assume the first step will be splitting the image:
byte [] source=....;
ImageWriter writer = com.icafe4j.image.ImageIO.getWriter(ImageType.GIF);
ByteArrayInputStream bis = new ByteArrayInputStream(source);
GIFTweaker.splitAnimatedGIF(bis, writer, "split");
bis.close();
What/how should i do next?

Thanks,
   Fredy

**Comment by dragon66** [comment]
@kfredy Not sure if I understand you right but you already have a large animated GIF and you want to create a small animated GIF, right?

**Comment by kfredy** [comment]
Yes exactly

**Comment by dragon66** [comment]
@kfredy This is how you can do it with ICAFE:
1. Create a FrameReader which is a subclass of GIFReader used to read animated GIF frame by frame and return them as GIFFrame instances.
`FrameReader reader = new FrameReader();
GIFFrame frame = null;
while ((frame = reader.getGIFFrameEx()) != null) {
// do something with the frame
} 
`
2. Initialize GIFTweaker to write animated GIF frame by frame like this:
// Start writing animated GIF frame by frame to save memory
		GIFWriter animatedGIFWriter = new GIFWriter();
// Apply dithering to 
		animatedGIFWriter.setImageParam(builder.applyDither(true).build());
		// Set logical screen width and height to zero to use first frame width and height 
		GIFTweaker.prepareForWrite(animatedGIFWriter, fout, 0, 0);
		for(int i = 0; i < images.length; i++)
			GIFTweaker.writeFrame(animatedGIFWriter, fout, images[i]);
		// wrap it up
		GIFTweaker.finishWrite(fout);

**Comment by kfredy** [comment]
Thanks for the information. I'll take a look later on. BTW i think it will be a great addition to the package. Thanks again

**Comment by dragon66** [comment]
@kfredy All the ingredients are there I just put them together for your specific case. If I see a relatively reasonable number of demands for this function, I can definitely add it to the package.
