### ISSUE TITLE
Tiff compression setting not honored

### ISSUE THREAD

**Issue by ben-manes** [dragon66/icafe#62]
An integration partner requested that we use CCITTFAX Group 4, which you implemented. However, they said that it the sample file was in fact PACKBITS. Using imagemagik `identify --verbose` it merely says RLE.

Digging into the code, [TIFFWriter.java#L679](https://github.com/dragon66/icafe/blob/master/src/com/icafe4j/image/writer/TIFFWriter.java#L679) appears to reset the `compression`. One would assume either (a) a failure or (b) the setting was honored and the image downgraded. Instead if the ImageParam is not set with `ImageColorType.BILEVEL` then it is upgraded to PACKBITS.

I believe honoring the user's settings would follow the _principle of least astonishment_.

**Comment by dragon66** [comment]
@ben-manes I have done some changes to check supported compression types for each image type. If certain compression type is not supported by an image type, a UnsupportedCompressionException will be thrown instead of falling back to the all potential PackBits compression.

**Comment by ben-manes** [comment]
Thanks, looks good!
