### ISSUE TITLE
IndexOutOfBoundsException risk in TIFFTweaker.writeMultipageTIFF()

### ISSUE THREAD

**Issue by THausherr** [dragon66/icafe#63]
The first loop (at line 3344) in TIFFTweaker.writeMultipageTIFF() may throw an exception which results in a stack trace being written. If the exception happens before `list.add(writer.getIFD());`, then list could be empty or too small at line 3358 in the second loop., which would result in an IndexOutOfBoundsException.

Same in the other method with the same name.

=> consider rethrowing the exception.

PS: ignore my mail from this morning. I was in a hurry.

**Comment by dragon66** [comment]
@THausherr Thanks for pointing this out. In stead of throw new exception, I would rather use the list size instead of the image array size to perform the second loop and in the end check to make sure at least we have one page in the list before writing it to the output. I have checked in the changes.

**Comment by THausherr** [comment]
But doesn't this bring the risk that if there's a (swallowed) exception, that not all pages are written and the user won't notice it?

**Comment by dragon66** [comment]
@THausherr That's a tradeoff. Depending on the users expectation. Sometimes it's better than nothing. If you have a concern, log something when the pages expected are not the same as the page actually created.

**Comment by dragon66** [comment]
After much struggling, I have finally decided to replace e.printStackTrace() with logging and throwing RuntimeException.

**Comment by THausherr** [comment]
Consider changing
`throw new RuntimeException("Failed writing page " + pageNumber);`
to
`throw new RuntimeException("Failed writing page " + pageNumber, e);`
for people who have turned logging off, or don't have access to it.

**Comment by dragon66** [comment]
@THausherr good point. Checked exception will be favored where at least partial result is acceptable like in multipage TIFF creation case.
