### ISSUE TITLE
Logging to a logger instead of System.out

### ISSUE THREAD

**Issue by jantekb** [dragon66/icafe#7]
Hi,

I came across your icafe library yesterday, when I was looking for a library to handle animated gifs. I would like to use it in my project, but the scattered logging to `System.out` is not too handy. I would expect a library to log via slf4j or logback, allowing it to seamlessly integrate with a bigger application. Do you have plans to change it? I am thinking about forking your project on github and making some changes.

On the other hand I am also writing this issue to get in touch with you and say big thanks for sharing this code!

Cheers,
Balazs

**Comment by dragon66** [comment]
Hi Balazs,

Thanks a lot for your interest in the code. The logging problem you are saying is definitely an issue which needs to be addressed. Only I am tied up with other high priority issues like metadata manipulation and JPEG reading support. The many System.out were mainly used for quick debug during the process of my early development. They will either go into metadata reading part or logging in the future.

I will put logging and managed building into the project at a later time, perhaps gradually. For now, if you want to use only the animated GIF part, you can fork the project and move the System.out found inside GIFTweaker.java, GIFReader.java and GIFWriter.java to logging.

Wen

**Comment by dragon66** [comment]
Replaced System.out with slf4j. Currently for testing purpose, log4j is used with logging level DEBUG. For production, turn off the logging, or set debugging level to WARN or ERROR for efficiency.
