### ISSUE TITLE
Remove TiffTag.WINDOWS_XP_KEYWORDS

### ISSUE THREAD

**Issue by ivanooi** [dragon66/icafe#70]
Hi, 

  I would like to clear Mircosoft keywords/tags field before I add a set of new keywords in.
but it did not clear and insert a new one in.

            exif.getImageIFD().removeField( TiffTag.WINDOWS_XP_KEYWORDS );
            
            exif.addImageField(TiffTag.WINDOWS_XP_KEYWORDS, FieldType.WINDOWSXP, "123" );
            exif.addImageField(TiffTag.WINDOWS_XP_KEYWORDS, FieldType.WINDOWSXP, "abc" );

Thanks again
Ivan

**Comment by ivanooi** [comment]
sorry , my fault.

You had done a very good job!

there is no need to call remove,...

exif.addImageField(TiffTag.WINDOWS_XP_KEYWORDS, FieldType.WINDOWSXP, "123;abc" );

thanks

**Comment by dragon66** [comment]
Great you figure it out.
