### ISSUE TITLE
Java out of memory exception

### ISSUE THREAD

**Issue by suncds-git** [dragon66/icafe#73]
When reading/writing images for large tiff files, receiving Out of Memory exception error.  This is occurring whenever multiple tiffs are being read, or written - TiffReader.read() TiffTweaker.insert pages() and TIFFTweaker.writeMultipageTIFF(.  I am working with some rather large multi page tiff files.  Is there a way to read/write a single tiff page at a time, and also append to existing tiff file?

**Comment by dragon66** [comment]
For inserting pages or writing multiple pages Tiff, there are methods available to handle pages one at a time. For inserting, the method combinations are prepareForInsert(), insertPage(called multiple times), finishInsert(); for writing multiple page Tiff, the corresponding methods are

**Comment by suncds-git** [comment]
Thanks, Wen for your quick reply.  I am reviewing the TiffReader.read() method,  This method is reading and storing all the images in the method's scope, which is causing an out of memory error.  You are correct that the first page is being returned from a List object.  I believe that I do need the capability of reading one tiff image at a time, so that the image may be read and then appended to the existing tiff file.

**Comment by dragon66** [comment]
I will write something similar to FrameReader for GIF image to work with TIFF pages one by one. Will check in the code tonight.
