### ISSUE TITLE
The POM for com.github.dragon66:icafe:jar:1.1-20151005.204941-1 is missing

### ISSUE THREAD

**Issue by kpassoubady** [dragon66/icafe#76]
[WARNING] The POM for com.github.dragon66:icafe:jar:1.1-20151005.204941-1 is mis
sing, no dependency information available
Downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/
dragon66/icafe/1.1-SNAPSHOT/icafe-1.1-20151005.204941-1.jar

The download from sonatype repository is failing, can you take a look:
<repositories>
		<repository>
			<id>oss.sonatype.org</id>
			<name>Sonatype Snapshot Repository</name>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
			<releases>
				<enabled>false</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>

**Comment by dragon66** [comment]
I am not sure why it is requesting the old version. I checked and see all the versions are for November and December 2017.

**Comment by ibrahimrajabli** [comment]
<dependency>
  <groupId>com.github.dragon66</groupId>
  <artifactId>icafe</artifactId>
  <version>1.1-SNAPSHOT</version>
</dependency> 

yes 1.1-SNAPSHOT is red. in dependencies  :)

**Comment by dragon66** [comment]
So is it working now?

**Comment by kpassoubady** [comment]
I have to comment all the code from iCafe to compile successfully, so that our automation still works without creating the gif files. I'll re-enable and see how it goes and update you.

**Comment by ibrahimrajabli** [comment]
yes it is working awesome. if my project will success i want donate you. 😊


________________________________

**Comment by dragon66** [comment]
@ibrahimrajabli thank you!

**Comment by dragon66** [comment]
Resumed publishing SNAPSHOT again. Hope things will go more smoothly.
