### ISSUE TITLE
metadata failed read large image but write ok

### ISSUE THREAD

**Issue by ivanooi** [dragon66/icafe#80]
Hi,

 I found out it had failed to read the metadata from a large image file (33MB)
but no problem in write.

Thanks

**Comment by dragon66** [comment]
Any details? What do mean by failed? Did you see any error message? If possible, put the image somewhere so that I can take a look.

**Comment by ivanooi** [comment]
sure. i can email. u

**Comment by ivanooi** [comment]
it throw java.lang.NegativeArraySizeException.

I managed to read the metadata using Apache Imaging lib.

**Comment by ivanooi** [comment]
i had email you the google drive link. thanks again

**Comment by dragon66** [comment]
@ivanooi Thanks. I found the issue: the image itself doesn't contain a EOI marker and further more, it contains a huge chunk of data which could be used by the camera software itself but is garbage for normal viewer/decoder.

I have done some changes to catch this as well as the case when the image actually contains no EOI marker.

See the latest code change for details. It should work for your case now.

**Comment by ivanooi** [comment]
great! I will give it a try. Thank you so much! :-D
