### ISSUE TITLE
Release snapshots again

### ISSUE THREAD

**Issue by ben-manes** [dragon66/icafe#83]
In #82, @dragon66 said that snapshots are no longer being pushed. Since formal releases are not being made, getting this back would be helpful.

A few options to consider:
1. [Jitpack](https://jitpack.io/#dragon66/icafe): This repository will build the repository, cache the results, and serve them as Maven dependencies. Currently it creates an empty jar because its trying to run the Maven build which was never setup.
2. Recover your credentials or use JCenter, and do any of...
  a. Start pushing snapshots manually again
  b. Setup TravisCI. It can push the snapshot when it runs the build after every commit.
  c. Start releasing formal builds on Maven Central
3. Push artifacts to your own repository, which can even be Github.

2b + 2c are ideal, but the most work. I think 2a is the easiest and best for you.

**Comment by ben-manes** [comment]
Any chance you can take a look at this? Otherwise I can try to fix your maven build for Jitpack to unblock a customer.

**Comment by ben-manes** [comment]
@dragon66 please merge #84

**Comment by dragon66** [comment]
Thanks a lot @ben-manes. Too busy at work these days. 

Anyway, the pull request is merged.

**Comment by ben-manes** [comment]
No worries, I'm too busy for my hobby projects too. Just hit this for work :)

If you like this approach, you might update the README to reference jitpack instead for snapshots.

**Comment by dragon66** [comment]
To be frank, I am not sure how jitpack works yet. Need a bit time to brush up on that.

**Comment by dragon66** [comment]
Snapshot for the latest code is now published to Maven again!
