### ISSUE TITLE
Limit in IPTC CAPTION_ABSTRACT

### ISSUE THREAD

**Issue by manu-aa-p** [dragon66/icafe#86]
Hi,

When I write IPTC tag CAPTION_ABSTRACT, it seems that I can not exceed 250 characters. 
From 251 characters, the tag content is no longer displayed in software such as ACDSee or XNView.

The following example works perfectly : 
```
String caption = "";
int size = 250;
for(int i = 0; i < size; i++) {
	caption += "A";
}
List<IPTCDataSet> iptcs = new ArrayList<IPTCDataSet>();
iptcs.add(new IPTCDataSet(IPTCApplicationTag.CAPTION_ABSTRACT, caption));

FileInputStream fis = new FileInputStream(new File("sourceFile.tif"));                                                
FileOutputStream fos = new FileOutputStream(new File("destFile.tif"));                                                

Metadata.insertIPTC(fis, fos, iptcs);

fis.close();                                                                                             
fos.close();
```
The result is correct : 

![image](https://user-images.githubusercontent.com/50253868/57172024-03e4a800-6e1b-11e9-8c98-99937cac0f34.png)

But as soon as the size exceeds 250 characters, the value is no longer readable : 
`int size = 251`

![image](https://user-images.githubusercontent.com/50253868/57172055-4f975180-6e1b-11e9-8966-b5ba733c5cdc.png)

Yet, if I write by hand in these tools, I can safely exceed 250 characters. 
And from what I read, this field is normally limited to 2000 characters, not 250.

**Comment by dragon66** [comment]
@manu-aa-p I did a test to insert caption into one of the images. After that, I can retrieve using ICAFE. Unfortunately I cannot install external software on my computer. So I went online and uploaded the image and got the following information:

![image](https://user-images.githubusercontent.com/7292053/57180223-95bcd700-6e54-11e9-874d-87ec7c6704a5.png)
 
From the screenshot, the caption is well exceeds 250 characters. Actually it is about 320 characters. I am not sure why the other tools not showing all the content though. As far as ICAFE is concerned, the field itself will be kept in a byte array and there is no limit on how long the string could be.

**Comment by manu-aa-p** [comment]
Hi,

Thanks a lot for your answer. I didn't know imageforensic, very interesting.
I've found another free software for IPTC reading. The comparison illustrates the same phenomenon. The IPTC value is here, but is not interpreted in the same way when writed by ICAFE.

long caption writed by XNView : 
![image](https://user-images.githubusercontent.com/50253868/57184548-3fd04980-6ebd-11e9-9fe7-0ddd0b32fb66.png)

long caption writed by ICAFE : 
![image](https://user-images.githubusercontent.com/50253868/57184556-5c6c8180-6ebd-11e9-9b5e-cd19fdcbf783.png)

The two images can be downloaded here for comparison  (26 Mo) : 
https://drive.google.com/file/d/1Z_-VqXaxH0XU0UlPe8dtnnbf8Y7b3zMb/view?usp=sharing

**Comment by dragon66** [comment]
@manu-aa-p I figure out half of the reason: for ICAFE, the preferred place to put IPTC is Photoshop IRB block. There is however, another TIFF field which can be used for IPTC data directly. I asked someone else to help debug the issue and see similar issues as you described. Then we used XnView to insert a new IPTC data with caption string length bigger than 250. This time XnView and Photoshop both show the data.

I then used ICAFE to view metadata and I found two sets of IPTC: one is what I added before to the image which is saved as part of Photoshop IRB; the other is saved directly as one of the TIFF tag field. The one which shows in the other viewers is the latter one.

This partially solved the issue: the other viewers prefer the TIFF tag and when there is no TIFF tag for the IPTC used, it will try to retrieve the Photoshop IRB block to see if there is one buried there.

I believe the above observation will explain your new funding.

Now the issue left is why as soon as the length of the string exceeds 250 characters, the viewers refuse to show the IPTC data in the Photoshop IRB block?

I looked at the spec again and still couldn't find any limitation apart from the 2000 characters restriction.

**Comment by manu-aa-p** [comment]
Hi,

Thank you for this explanation and more widely for your responsiveness.
I found these pages about ExifTools that relate to the problem you are describing. The location of the information may vary in the file and the reading softwares may not find it.

http://owl.phy.queensu.ca/~phil/exiftool/TagNames/IPTC.html

>Note that it is not uncommon for IPTC to be found in non-standard locations in JPEG and TIFF-based images. When reading, the family 1 group name has a number added for non-standard IPTC ("IPTC2", "IPTC3", etc), but when writing only "IPTC" may be specified as the group. To keep the IPTC consistent, ExifTool updates tags in all existing IPTC locations, but will create a new IPTC group only in the standard location.

https://forums.adobe.com/thread/2540298

>In the “good” 3.tif file, there are two sets of entries, IPTC and IPTC2 – however I believe the IPTC2 entries are questionable. However in the “bad” 4.tif file, there are only IPTC2 entries with no IPTC entries.

**Comment by dragon66** [comment]
@manu-aa-p thanks for the information. As far as I know, there is no specification that dictates where is the standard place to put IPTC data in TIFF file. Only there is a specific TIFF field for IPTC. This is different between TIFF and JPEG. Theoretically I can see at least 3 places including as part of XMP to store IPTC data.

On the other hand, different softwares especially those which are not created specifically for handling metadata will definitely have a hard time to dig everything out from all locations.

Anyway, seems like the TIFF IPTC tag is the commonly accepted place among all the softwares to put IPTC data. After my latest commit, I can see the long caption shown as title in Windows Photo Viewer which is a good sign of I am on the right track.

Let me know if it works for your case.
