### ISSUE TITLE
How to read "Rights Usage Terms"?

### ISSUE THREAD

**Issue by coolboy** [dragon66/icafe#88]
We want to keep all the copyright fields, but I just can't find a way in icafe to read "Rights Usage Terms" as example image below?

<img width="924" alt="Screen Shot 2019-06-25 at 5 49 21 PM" src="https://user-images.githubusercontent.com/404691/60143127-b11bd280-9771-11e9-9c56-ee6176304fe8.png">

**Comment by coolboy** [comment]
![iptc_demopic1](https://user-images.githubusercontent.com/404691/60143181-ddcfea00-9771-11e9-82ef-30d4dffc7b3c.jpg)
Uploading the example jpg

**Comment by dragon66** [comment]
@coolboy The IPTC metadata implementation in ICFE is for IPTC-NAA only which is a legacy of the new XMP schema based IPTC. As a result, you will not be able to see all the IPTC fields defined by IPTC spec from the IPTC metadata extracted by ICAFE.

I tested the image you provided, the more detailed information including "Rights Usage Terms" are in the XMP metadata which ICAFE also extracted.

**Comment by coolboy** [comment]
Hi @dragon66 

Thanks for your reply this is what I found out as well

BTW how to loop through or get the raw xml from XMP using icafe?

By checking your example
https://github.com/dragon66/icafe/blob/master/src/com/icafe4j/test/TestMetadata.java#L68

I can't find the MetadataEntry in the current SNAPSHOT? Do we need to publish 1.2?

Thank you again

**Comment by dragon66** [comment]
@coolboy You can get the DOM tree by calling getMergedDocument() on an XMP instance. It will return a Document object which if you want, you can call XMLUtils.serializeToString(Document doc) or XMLUtilss.serializeToByteArray(Document doc) which are just as the names suggested will return either a XML string of the DOM tree or a byte array of the DOM tree. You can further save them to a file if you want.

The SNAPSHOT is quite out of sync with the current repository. I need to setup the build process in a different computer which has no restriction as the one I am using. There is an issue opened for this by some other user. I will update that issue after I push the new SNAPSHOT.

**Comment by coolboy** [comment]
thank you!
