### ISSUE TITLE
Is it possible to store multiple small size (thumbnail) in one photo?

### ISSUE THREAD

**Issue by ivanooi** [dragon66/icafe#89]
Hi, 

Is it possible to store multiple small size (thumbnail) in one photo? I'm thinking to do facial recognition indexing..

Thanks

**Comment by dragon66** [comment]
Not the public way but you can define your own XMP schema to suite your requirement.

**Comment by ivanooi** [comment]
you mean store thumbnail as binary array in XMP?

**Comment by dragon66** [comment]
It doesn't matter how you save them as long as you can retrieve them back. Google same them as Base64 encoded PNG images.

**Comment by dragon66** [comment]
Here is a link to StackOverflow question I answered a while ago related to Google Cardboard Camera app and Cardbox Camera images:
[Reading JPG file's XMP metadata](https://stackoverflow.com/questions/23253281/reading-jpg-files-xmp-metadata/28788888#28788888)

**Comment by ivanooi** [comment]
good point! I think that what I need. I can store faces in XMP. 

Thanks
