### ISSUE TITLE
Publish on Maven central or Bintray

### ISSUE THREAD

**Issue by nightscape** [dragon66/icafe#9]
Hi!

For easier consumption, it would be great if the Jar were hosted somewhere.
Maven central is the standard, but publishing to Bintray is much easier.
Anyway, some place where one could automatically retrieve the Jar via Maven, SBT, ... would be great!

Thanks
  Martin

**Comment by dragon66** [comment]
Hi, Martin,

Thanks a lot for your comment. Looks like it's time for me to do some work to ease the build and publish it for ease usage

**Comment by RevanProdigalKnight** [comment]
Has anything been done about this?

**Comment by dragon66** [comment]
Hi RevanProdigalKnight:

Not yet. I had never worked with Maven before and still busy with other stuff. Is it possible you or someone else help doing this?

**Comment by dragon66** [comment]
Planning to publish a SNAPSHOT Maven repository soon

**Comment by dragon66** [comment]
Added ant task to publish on Maven.
