### ISSUE TITLE
tiff格式图片加入xmp

### ISSUE THREAD

**Issue by zhoukai0203** [dragon66/icafe#93]
tiff格式图片加入xmp 文件会不断的变大，jpeg和png格式的没有问题，都是添加xmp

**Comment by dragon66** [comment]
不太明白你说的。具体给个例子。

**Comment by dragon66** [comment]
@zhoukai0203 问题找到了。tiff除了exif外，其它的metadata插入都有类似的问题。原因是有一个writeOffset我设错了，所以插入元数据后图像尺寸会加倍。问题已经修复了。
